# Generated by Django 4.0.5 on 2022-07-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudo',
            name='categoria',
            field=models.CharField(choices=[('CULTOS', 'Cultos'), ('MOVER_DO_ESPIRITO_SANTO', 'Mover do Espirito Santo'), ('PREGACOES', 'Pregações'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros'), ('DISCIPULADO', 'Discipulado')], max_length=25),
        ),
    ]
